title: thesis? idk?
name: thesis? idk?
author: Chris Carin
description: a blog for 4th year workshop at OCADU
url: https://cheesoup.github.io
baseurl: /GRPH
plugins:
  - jekyll-feed
  - jekyll-seo-tag
sass:
  style: compressed
exclude: [serve.bat]
