title: thesis? idk?
name: thesis? idk?
author: Chris
description: a blog about 4th year GRPH workshop @ OCADU
url: https://cheesoup.github.io
baseurl: /GRPH
tag_page_layout: tags
tag_page_dir: tags
plugins: ["emoji_for_jekyll"]
